// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RcHAaFPun5OY8UNw7yYjoxgFeWyIaAg',
    appId: '1:1032086160402:web:02875763787625403e84cb',
    messagingSenderId: '1032086160402',
    projectId: 'katgame-2129d',
    authDomain: 'katgame-2129d.firebaseapp.com',
    storageBucket: 'katgame-2129d.appspot.com',
    measurementId: 'G-Z3SJVSEGJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMljpxH0RCXT4nFakkcXJJDfpGUU8lRw',
    appId: '1:1032086160402:android:8ddb0af20354a4293e84cb',
    messagingSenderId: '1032086160402',
    projectId: 'katgame-2129d',
    storageBucket: 'katgame-2129d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3YQzOKhw0jX-xmV2zkA0-c7HGGpc3XM',
    appId: '1:1032086160402:ios:b5f3ce0bbfa01e2a3e84cb',
    messagingSenderId: '1032086160402',
    projectId: 'katgame-2129d',
    storageBucket: 'katgame-2129d.appspot.com',
    iosClientId:
        '1032086160402-ts0ts02s64euiioab4v9a3abmq550g81.apps.googleusercontent.com',
    iosBundleId: 'com.example.katGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3YQzOKhw0jX-xmV2zkA0-c7HGGpc3XM',
    appId: '1:1032086160402:ios:b5f3ce0bbfa01e2a3e84cb',
    messagingSenderId: '1032086160402',
    projectId: 'katgame-2129d',
    storageBucket: 'katgame-2129d.appspot.com',
    iosClientId:
        '1032086160402-ts0ts02s64euiioab4v9a3abmq550g81.apps.googleusercontent.com',
    iosBundleId: 'com.example.katGame',
  );
}
